### PR TITLE
[Style] Align if modifiers based on surrounding code

### PR DESCRIPTION
**Pull request by ashmaroli**

### CODE REVIEW

**Comment by agriffis** [comment]
I'm glad you're interested in rubypants, but it's not clear to me that fiddling with the spacing is especially useful. Are there bugs or features you have in mind that you hope to work on?

**Comment by ashmaroli** [comment]
I plan to send a PR to Jekyll to have their `smartify` filter use `RubyPants` instead of `Kramdown`..
A simple benchmark run seemed to show that RubyPants is ~5x faster than Kramdown..

So, came across these discrepancies while I was skimming through RubyPants' code...

**Comment by agriffis** [comment]
Have you seen this? https://github.com/scampersand/jekyll-pants

**Comment by ashmaroli** [comment]
> Have you seen this?

Yep. its mentioned in the README

**Comment by agriffis** [comment]
Okay, great. Just wanted to check. I dove deep into this stuff (such as the `smartify` filter) at one point, but it's been a while since I've looked closely.

Let me know when you have the jekyll PR, I'm curious to see how it goes!

**Pull request merged**
