### PR TITLE
Allow option to output unicode characters

### PR DESCRIPTION
**Pull request by gregfedorov**

### CODE REVIEW

**Comment by agriffis** [comment]
Great idea!  Needs a few tweaks and a test.  You might look at https://github.com/jmcnevin/rubypants/pull/15 for a pattern to follow... this should be very similar to how that was added.

**Comment by gregfedorov** [comment]
I added a quick test and fixed the dash test that was failing earlier, aslo simplified the file structure a bit so that there's no superclass mismatch error anymore.

**Comment by agriffis** [comment]
Thanks. I'll be able to look closer and merge in a few days

**Comment by agriffis** [comment]
Thanks Greg. I split this into two changes:

* Commit 9a38a0da9e8dce8ae99b579ff739224acbaac7b1 adds options `:character_entities`. I used Ruby's unicode escape syntax instead of embedding characters directly—this is especially for the `:character_spaces` option.

* Pull request #17 adds the `RubyPantsVersion` module and restructures the repo as you suggested to avoid the superclass mismatch. I'll merge this once the tests run in Travis.

Let me know what you think, and I'll plan to release this as 0.7.0

**Comment by agriffis** [comment]
@gregfedorov By the way, the email address you're using for commits isn't registered with your github account, so commits don't link properly for you. If you're interested, the setting is at https://github.com/settings/emails

**Comment by gregfedorov** [comment]
Thanks for the tip! I didn't know commit emails were used for that.

**Pull request closed without merging**
